/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_home (void)
{
  GtkWidget *home;
  GtkWidget *fixed1;
  GtkWidget *image13;
  GtkWidget *label1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label10;
  GtkWidget *button5;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label11;

  home = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (home), _("Home"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (home), fixed1);
  gtk_widget_set_size_request (fixed1, 616, 400);

  image13 = create_pixmap (home, "equipement-agricole-style-isometrique_96318-6497.jpeg");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed1), image13, 0, 0);
  gtk_widget_set_size_request (image13, 624, 408);

  label1 = gtk_label_new (_("Gestion des equipements agricoles"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 184, 56);
  gtk_widget_set_size_request (label1, 697, 64);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label1), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label1), 0.5, 0.43);
  gtk_misc_set_padding (GTK_MISC (label1), 3, 0);
  gtk_label_set_width_chars (GTK_LABEL (label1), 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 176, 120);
  gtk_widget_set_size_request (button1, 260, 68);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Ajouter un equipement"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox1), label10, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1), button5, 176, 248);
  gtk_widget_set_size_request (button5, 260, 68);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button5), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Afficher les equipements"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox2), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (home, home, "home");
  GLADE_HOOKUP_OBJECT (home, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (home, image13, "image13");
  GLADE_HOOKUP_OBJECT (home, label1, "label1");
  GLADE_HOOKUP_OBJECT (home, button1, "button1");
  GLADE_HOOKUP_OBJECT (home, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (home, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (home, image1, "image1");
  GLADE_HOOKUP_OBJECT (home, label10, "label10");
  GLADE_HOOKUP_OBJECT (home, button5, "button5");
  GLADE_HOOKUP_OBJECT (home, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (home, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (home, image2, "image2");
  GLADE_HOOKUP_OBJECT (home, label11, "label11");

  return home;
}

GtkWidget*
create_ajout (void)
{
  GtkWidget *ajout;
  GtkWidget *fixed2;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *id;
  GtkWidget *marque;
  GtkWidget *label4;
  GtkWidget *label20;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *label21;
  GtkWidget *retourajout;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label15;
  GtkWidget *button6;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label14;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton3;
  GSList *radiobutton3_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton4;
  GtkWidget *combobox1;

  ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout), _("ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajout), fixed2);
  gtk_widget_set_size_request (fixed2, 402, 475);

  label2 = gtk_label_new (_("ID"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 176, 16);
  gtk_widget_set_size_request (label2, 41, 17);

  label3 = gtk_label_new (_("marque"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 160, 88);
  gtk_widget_set_size_request (label3, 80, 16);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed2), id, 128, 40);
  gtk_widget_set_size_request (id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  marque = gtk_entry_new ();
  gtk_widget_show (marque);
  gtk_fixed_put (GTK_FIXED (fixed2), marque, 128, 112);
  gtk_widget_set_size_request (marque, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (marque), 8226);

  label4 = gtk_label_new (_("Etat :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 104, 152);
  gtk_widget_set_size_request (label4, 216, 24);

  label20 = gtk_label_new (_("Disponibilit\303\251 :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed2), label20, 152, 208);
  gtk_widget_set_size_request (label20, 112, 24);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed2), jour, 72, 312);
  gtk_widget_set_size_request (jour, 60, 27);

  annee_adj = gtk_adjustment_new (2020, 1900, 3000, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed2), annee, 264, 312);
  gtk_widget_set_size_request (annee, 65, 27);

  label21 = gtk_label_new (_("Date D'ajout :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 128, 272);
  gtk_widget_set_size_request (label21, 152, 24);

  retourajout = gtk_button_new ();
  gtk_widget_show (retourajout);
  gtk_fixed_put (GTK_FIXED (fixed2), retourajout, 152, 400);
  gtk_widget_set_size_request (retourajout, 102, 39);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (retourajout), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox6), label15, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 152, 352);
  gtk_widget_set_size_request (button6, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button6), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox5), label14, FALSE, FALSE, 0);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("fonctionne"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 88, 184);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("DIsponible"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3, 88, 240);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("en panne"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 224, 184);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("non disponible"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton4, 224, 240);
  gtk_widget_set_size_request (radiobutton4, 128, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1, 176, 312);
  gtk_widget_set_size_request (combobox1, 48, 27);
  gtk_container_set_border_width (GTK_CONTAINER (combobox1), 2);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("12"));

  g_signal_connect ((gpointer) retourajout, "clicked",
                    G_CALLBACK (on_retourajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (ajout, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajout, label2, "label2");
  GLADE_HOOKUP_OBJECT (ajout, label3, "label3");
  GLADE_HOOKUP_OBJECT (ajout, id, "id");
  GLADE_HOOKUP_OBJECT (ajout, marque, "marque");
  GLADE_HOOKUP_OBJECT (ajout, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajout, label20, "label20");
  GLADE_HOOKUP_OBJECT (ajout, jour, "jour");
  GLADE_HOOKUP_OBJECT (ajout, annee, "annee");
  GLADE_HOOKUP_OBJECT (ajout, label21, "label21");
  GLADE_HOOKUP_OBJECT (ajout, retourajout, "retourajout");
  GLADE_HOOKUP_OBJECT (ajout, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajout, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajout, image6, "image6");
  GLADE_HOOKUP_OBJECT (ajout, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajout, button6, "button6");
  GLADE_HOOKUP_OBJECT (ajout, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (ajout, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ajout, image5, "image5");
  GLADE_HOOKUP_OBJECT (ajout, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajout, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (ajout, combobox1, "combobox1");

  return ajout;
}

GtkWidget*
create_search (void)
{
  GtkWidget *search;
  GtkWidget *fixed4;
  GtkWidget *id;
  GtkWidget *iD;
  GtkWidget *trouver;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label16;
  GtkWidget *label9;
  GtkWidget *retoursearch;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label17;

  search = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (search), _("Search"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (search), fixed4);
  gtk_widget_set_size_request (fixed4, 479, 328);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed4), id, 160, 72);
  gtk_widget_set_size_request (id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  iD = gtk_label_new (_("ID"));
  gtk_widget_show (iD);
  gtk_fixed_put (GTK_FIXED (fixed4), iD, 216, 40);
  gtk_widget_set_size_request (iD, 41, 17);

  trouver = gtk_button_new ();
  gtk_widget_show (trouver);
  gtk_fixed_put (GTK_FIXED (fixed4), trouver, 192, 104);
  gtk_widget_set_size_request (trouver, 95, 37);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (trouver), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Trouver"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox7), label16, FALSE, FALSE, 0);

  label9 = gtk_label_new ("");
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed4), label9, 0, 192);
  gtk_widget_set_size_request (label9, 472, 120);
  gtk_misc_set_padding (GTK_MISC (label9), 11, 0);

  retoursearch = gtk_button_new ();
  gtk_widget_show (retoursearch);
  gtk_fixed_put (GTK_FIXED (fixed4), retoursearch, 192, 144);
  gtk_widget_set_size_request (retoursearch, 95, 37);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (retoursearch), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox8), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) trouver, "clicked",
                    G_CALLBACK (on_trouver_clicked),
                    NULL);
  g_signal_connect ((gpointer) retoursearch, "clicked",
                    G_CALLBACK (on_retoursearch_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (search, search, "search");
  GLADE_HOOKUP_OBJECT (search, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (search, id, "id");
  GLADE_HOOKUP_OBJECT (search, iD, "iD");
  GLADE_HOOKUP_OBJECT (search, trouver, "trouver");
  GLADE_HOOKUP_OBJECT (search, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (search, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (search, image7, "image7");
  GLADE_HOOKUP_OBJECT (search, label16, "label16");
  GLADE_HOOKUP_OBJECT (search, label9, "label9");
  GLADE_HOOKUP_OBJECT (search, retoursearch, "retoursearch");
  GLADE_HOOKUP_OBJECT (search, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (search, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (search, image8, "image8");
  GLADE_HOOKUP_OBJECT (search, label17, "label17");

  return search;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed5;
  GtkWidget *id;
  GtkWidget *button9;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label18;
  GtkWidget *retournermodifier;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label19;
  GtkWidget *label7;
  GtkWidget *radiobutton5;
  GSList *radiobutton5_group = NULL;
  GtkWidget *radiobutton6;
  GtkWidget *label8;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("Modification"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (modifier), fixed5);
  gtk_widget_set_size_request (fixed5, 376, 285);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed5), id, 120, 56);
  gtk_widget_set_size_request (id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed5), button9, 136, 176);
  gtk_widget_set_size_request (button9, 112, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox9), label18, FALSE, FALSE, 0);

  retournermodifier = gtk_button_new ();
  gtk_widget_show (retournermodifier);
  gtk_fixed_put (GTK_FIXED (fixed5), retournermodifier, 136, 224);
  gtk_widget_set_size_request (retournermodifier, 112, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (retournermodifier), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox10), label19, FALSE, FALSE, 0);

  label7 = gtk_label_new (_("ID"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed5), label7, 176, 32);
  gtk_widget_set_size_request (label7, 41, 17);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Fonctionne"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton5, 64, 136);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("En panne"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton6, 216, 136);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  label8 = gtk_label_new (_("Etat"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed5), label8, 160, 96);
  gtk_widget_set_size_request (label8, 72, 24);

  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) retournermodifier, "clicked",
                    G_CALLBACK (on_retournermodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (on_radiobutton6_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (modifier, id, "id");
  GLADE_HOOKUP_OBJECT (modifier, button9, "button9");
  GLADE_HOOKUP_OBJECT (modifier, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifier, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifier, image9, "image9");
  GLADE_HOOKUP_OBJECT (modifier, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifier, retournermodifier, "retournermodifier");
  GLADE_HOOKUP_OBJECT (modifier, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modifier, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (modifier, image10, "image10");
  GLADE_HOOKUP_OBJECT (modifier, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifier, label7, "label7");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (modifier, label8, "label8");

  return modifier;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed6;
  GtkWidget *treeview1;
  GtkWidget *image16;
  GtkWidget *retourner;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label13;
  GtkWidget *sup;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label26;
  GtkWidget *modif;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label27;
  GtkWidget *button4;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image17;
  GtkWidget *label28;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window1), fixed6);
  gtk_widget_set_size_request (fixed6, 785, 530);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview1, 32, 48);
  gtk_widget_set_size_request (treeview1, 444, 407);

  image16 = create_pixmap (window1, "932b14cff1703f7707edda44d397546e.jpeg");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed6), image16, 0, 0);
  gtk_widget_set_size_request (image16, 785, 565);

  retourner = gtk_button_new ();
  gtk_widget_show (retourner);
  gtk_fixed_put (GTK_FIXED (fixed6), retourner, 192, 496);
  gtk_widget_set_size_request (retourner, 97, 30);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (retourner), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox4), label13, FALSE, FALSE, 0);

  sup = gtk_button_new ();
  gtk_widget_show (sup);
  gtk_fixed_put (GTK_FIXED (fixed6), sup, 584, 120);
  gtk_widget_set_size_request (sup, 160, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (sup), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("   Supprimer"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox13), label26, FALSE, FALSE, 0);

  modif = gtk_button_new ();
  gtk_widget_show (modif);
  gtk_fixed_put (GTK_FIXED (fixed6), modif, 584, 192);
  gtk_widget_set_size_request (modif, 160, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (modif), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox14), label27, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed6), button4, 584, 264);
  gtk_widget_set_size_request (button4, 160, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button4), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox15), image17, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox15), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) retourner, "clicked",
                    G_CALLBACK (on_retourner_clicked),
                    NULL);
  g_signal_connect ((gpointer) sup, "clicked",
                    G_CALLBACK (on_sup_clicked),
                    NULL);
  g_signal_connect ((gpointer) modif, "clicked",
                    G_CALLBACK (on_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, image16, "image16");
  GLADE_HOOKUP_OBJECT (window1, retourner, "retourner");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, sup, "sup");
  GLADE_HOOKUP_OBJECT (window1, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, modif, "modif");
  GLADE_HOOKUP_OBJECT (window1, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, image15, "image15");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, label28, "label28");

  return window1;
}

GtkWidget*
create_success (void)
{
  GtkWidget *success;
  GtkWidget *fixed7;
  GtkWidget *retoursuccess;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label23;
  GtkWidget *label22;

  success = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (success), _("success"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (success), fixed7);
  gtk_widget_set_size_request (fixed7, 406, 212);

  retoursuccess = gtk_button_new ();
  gtk_widget_show (retoursuccess);
  gtk_fixed_put (GTK_FIXED (fixed7), retoursuccess, 152, 144);
  gtk_widget_set_size_request (retoursuccess, 102, 39);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (retoursuccess), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox11), label23, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("L'objet a \303\251t\303\251 ajout\303\251 avec succ\303\251s !"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed7), label22, 64, 56);
  gtk_widget_set_size_request (label22, 280, 48);

  g_signal_connect ((gpointer) retoursuccess, "clicked",
                    G_CALLBACK (on_retoursuccess_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (success, success, "success");
  GLADE_HOOKUP_OBJECT (success, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (success, retoursuccess, "retoursuccess");
  GLADE_HOOKUP_OBJECT (success, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (success, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (success, image11, "image11");
  GLADE_HOOKUP_OBJECT (success, label23, "label23");
  GLADE_HOOKUP_OBJECT (success, label22, "label22");

  return success;
}

GtkWidget*
create_failed (void)
{
  GtkWidget *failed;
  GtkWidget *fixed8;
  GtkWidget *label24;
  GtkWidget *errorredo;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label25;

  failed = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (failed), _("Error"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (failed), fixed8);
  gtk_widget_set_size_request (fixed8, 401, 182);

  label24 = gtk_label_new (_("cet identifiant existe d\303\251j\303\240"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed8), label24, 96, 48);
  gtk_widget_set_size_request (label24, 216, 48);

  errorredo = gtk_button_new ();
  gtk_widget_show (errorredo);
  gtk_fixed_put (GTK_FIXED (fixed8), errorredo, 136, 112);
  gtk_widget_set_size_request (errorredo, 136, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (errorredo), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("r\303\251essayer"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox12), label25, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) errorredo, "clicked",
                    G_CALLBACK (on_errorredo_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (failed, failed, "failed");
  GLADE_HOOKUP_OBJECT (failed, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (failed, label24, "label24");
  GLADE_HOOKUP_OBJECT (failed, errorredo, "errorredo");
  GLADE_HOOKUP_OBJECT (failed, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (failed, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (failed, image12, "image12");
  GLADE_HOOKUP_OBJECT (failed, label25, "label25");

  return failed;
}

