/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_home (void)
{
  GtkWidget *home;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *button5;
  GtkWidget *button3;
  GtkWidget *button4;

  home = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (home), _("Home"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (home), fixed1);

  label1 = gtk_label_new (_("Gestion des equipements agricoles"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 143, 32);
  gtk_widget_set_size_request (label1, 312, 80);

  button1 = gtk_button_new_with_mnemonic (_("Ajouter un equipement"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 192, 120);
  gtk_widget_set_size_request (button1, 224, 48);

  button2 = gtk_button_new_with_mnemonic (_("Modifier un equipement"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 192, 176);
  gtk_widget_set_size_request (button2, 224, 48);

  button5 = gtk_button_new_with_mnemonic (_("Afficher les equipements"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1), button5, 192, 344);
  gtk_widget_set_size_request (button5, 224, 48);

  button3 = gtk_button_new_with_mnemonic (_("Supprimer un equipement"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 192, 232);
  gtk_widget_set_size_request (button3, 224, 48);

  button4 = gtk_button_new_with_mnemonic (_("Chercher un equipement existant"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 192, 288);
  gtk_widget_set_size_request (button4, 224, 48);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (home, home, "home");
  GLADE_HOOKUP_OBJECT (home, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (home, label1, "label1");
  GLADE_HOOKUP_OBJECT (home, button1, "button1");
  GLADE_HOOKUP_OBJECT (home, button2, "button2");
  GLADE_HOOKUP_OBJECT (home, button5, "button5");
  GLADE_HOOKUP_OBJECT (home, button3, "button3");
  GLADE_HOOKUP_OBJECT (home, button4, "button4");

  return home;
}

GtkWidget*
create_ajout (void)
{
  GtkWidget *ajout;
  GtkWidget *fixed2;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *id;
  GtkWidget *marque;
  GtkWidget *button6;
  GtkWidget *etat;
  GtkWidget *label4;

  ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout), _("ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajout), fixed2);

  label2 = gtk_label_new (_("ID"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 176, 16);
  gtk_widget_set_size_request (label2, 41, 17);

  label3 = gtk_label_new (_("marque"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 160, 88);
  gtk_widget_set_size_request (label3, 80, 16);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed2), id, 128, 40);
  gtk_widget_set_size_request (id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  marque = gtk_entry_new ();
  gtk_widget_show (marque);
  gtk_fixed_put (GTK_FIXED (fixed2), marque, 128, 112);
  gtk_widget_set_size_request (marque, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (marque), 8226);

  button6 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 176, 272);
  gtk_widget_set_size_request (button6, 66, 29);

  etat = gtk_entry_new ();
  gtk_widget_show (etat);
  gtk_fixed_put (GTK_FIXED (fixed2), etat, 128, 184);
  gtk_widget_set_size_request (etat, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (etat), 8226);

  label4 = gtk_label_new (_("Etat (p:en panne , f:fonctionne)"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 104, 152);
  gtk_widget_set_size_request (label4, 216, 24);

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (ajout, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajout, label2, "label2");
  GLADE_HOOKUP_OBJECT (ajout, label3, "label3");
  GLADE_HOOKUP_OBJECT (ajout, id, "id");
  GLADE_HOOKUP_OBJECT (ajout, marque, "marque");
  GLADE_HOOKUP_OBJECT (ajout, button6, "button6");
  GLADE_HOOKUP_OBJECT (ajout, etat, "etat");
  GLADE_HOOKUP_OBJECT (ajout, label4, "label4");

  return ajout;
}

GtkWidget*
create_delete (void)
{
  GtkWidget *delete;
  GtkWidget *fixed3;
  GtkWidget *label5;
  GtkWidget *entry1;
  GtkWidget *delete_button;

  delete = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (delete), _("Delete"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (delete), fixed3);

  label5 = gtk_label_new (_("ID"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 96, 64);
  gtk_widget_set_size_request (label5, 200, 41);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 120, 104);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  delete_button = gtk_button_new_with_mnemonic (_("Delete"));
  gtk_widget_show (delete_button);
  gtk_fixed_put (GTK_FIXED (fixed3), delete_button, 168, 160);
  gtk_widget_set_size_request (delete_button, 66, 29);

  g_signal_connect ((gpointer) delete_button, "clicked",
                    G_CALLBACK (on_delete_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (delete, delete, "delete");
  GLADE_HOOKUP_OBJECT (delete, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (delete, label5, "label5");
  GLADE_HOOKUP_OBJECT (delete, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (delete, delete_button, "delete_button");

  return delete;
}

GtkWidget*
create_search (void)
{
  GtkWidget *search;
  GtkWidget *fixed4;
  GtkWidget *iD;
  GtkWidget *entry2;
  GtkWidget *trouver;

  search = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (search), _("Search"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (search), fixed4);

  iD = gtk_label_new (_("ID"));
  gtk_widget_show (iD);
  gtk_fixed_put (GTK_FIXED (fixed4), iD, 176, 80);
  gtk_widget_set_size_request (iD, 41, 17);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed4), entry2, 128, 112);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  trouver = gtk_button_new_with_mnemonic (_("Trouver"));
  gtk_widget_show (trouver);
  gtk_fixed_put (GTK_FIXED (fixed4), trouver, 168, 160);
  gtk_widget_set_size_request (trouver, 66, 29);

  g_signal_connect ((gpointer) trouver, "clicked",
                    G_CALLBACK (on_trouver_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (search, search, "search");
  GLADE_HOOKUP_OBJECT (search, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (search, iD, "iD");
  GLADE_HOOKUP_OBJECT (search, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (search, trouver, "trouver");

  return search;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed5;
  GtkWidget *label7;
  GtkWidget *entry3;
  GtkWidget *label8;
  GtkWidget *entry4;
  GtkWidget *button9;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("Modification"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (modifier), fixed5);

  label7 = gtk_label_new (_("ID"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed5), label7, 168, 48);
  gtk_widget_set_size_request (label7, 41, 17);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed5), entry3, 120, 72);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label8 = gtk_label_new (_("Etat"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed5), label8, 168, 104);
  gtk_widget_set_size_request (label8, 41, 17);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed5), entry4, 120, 128);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  button9 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed5), button9, 136, 176);
  gtk_widget_set_size_request (button9, 112, 40);

  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (modifier, label7, "label7");
  GLADE_HOOKUP_OBJECT (modifier, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (modifier, label8, "label8");
  GLADE_HOOKUP_OBJECT (modifier, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (modifier, button9, "button9");

  return modifier;
}

