/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_home (void);
GtkWidget* create_ajout (void);
GtkWidget* create_search (void);
GtkWidget* create_modifier (void);
GtkWidget* create_window1 (void);
