/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_plantation_vegetale (void)
{
  GtkWidget *plantation_vegetale;
  GtkWidget *fixed1;
  GtkWidget *bienvenue;
  GtkWidget *ajouter;
  GtkWidget *afficher;

  plantation_vegetale = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (plantation_vegetale), _("plantation vegetale"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (plantation_vegetale), fixed1);

  bienvenue = gtk_label_new (_("Bienvenue "));
  gtk_widget_show (bienvenue);
  gtk_fixed_put (GTK_FIXED (fixed1), bienvenue, 200, 48);
  gtk_widget_set_size_request (bienvenue, 150, 30);

  ajouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 200, 100);
  gtk_widget_set_size_request (ajouter, 150, 30);

  afficher = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 200, 200);
  gtk_widget_set_size_request (afficher, 150, 30);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_Ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (plantation_vegetale, plantation_vegetale, "plantation_vegetale");
  GLADE_HOOKUP_OBJECT (plantation_vegetale, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (plantation_vegetale, bienvenue, "bienvenue");
  GLADE_HOOKUP_OBJECT (plantation_vegetale, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (plantation_vegetale, afficher, "afficher");

  return plantation_vegetale;
}

GtkWidget*
create_fenetre_ajout (void)
{
  GtkWidget *fenetre_ajout;
  GtkWidget *fixed2;
  GtkWidget *label1;
  GtkWidget *type;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *quantite;
  GtkWidget *label6;
  GtkWidget *label5;
  GtkWidget *label4;
  GtkWidget *ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *afficher;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label8;
  GtkWidget *label2;
  GtkWidget *label3;

  fenetre_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajout), _("Ajouter une plantation "));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_ajout), fixed2);

  label1 = gtk_label_new (_("Formulaire d'ajout d'une nouvelle plante "));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 96, 16);
  gtk_widget_set_size_request (label1, 500, 30);

  type = gtk_entry_new ();
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed2), type, 250, 100);
  gtk_widget_set_size_request (type, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (type), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed2), jour, 256, 152);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed2), mois, 368, 150);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (1990, 1990, 2020, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed2), annee, 528, 152);
  gtk_widget_set_size_request (annee, 60, 27);

  quantite = gtk_entry_new ();
  gtk_widget_show (quantite);
  gtk_fixed_put (GTK_FIXED (fixed2), quantite, 250, 200);
  gtk_widget_set_size_request (quantite, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (quantite), 8226);

  label6 = gtk_label_new (_("quantit\303\251 :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 100, 200);
  gtk_widget_set_size_request (label6, 150, 30);

  label5 = gtk_label_new (_("ann\303\251e :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 424, 150);
  gtk_widget_set_size_request (label5, 150, 30);

  label4 = gtk_label_new (_("mois :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 272, 150);
  gtk_widget_set_size_request (label4, 150, 30);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouter, 300, 350);
  gtk_widget_set_size_request (ajouter, 150, 30);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed2), afficher, 550, 350);
  gtk_widget_set_size_request (afficher, 150, 30);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (afficher), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox2), label8, FALSE, FALSE, 0);

  label2 = gtk_label_new (_("Type"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 100, 100);
  gtk_widget_set_size_request (label2, 150, 30);

  label3 = gtk_label_new (_("Saison :"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 100, 150);
  gtk_widget_set_size_request (label3, 150, 30);

  jour = gtk_label_new (_("jour :"));
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed2), jour, 160, 152);
  gtk_widget_set_size_request (jour, 150, 30);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajout, fenetre_ajout, "fenetre_ajout");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label1, "label1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, type, "type");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, jour, "jour");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, mois, "mois");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, annee, "annee");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, quantite, "quantite");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label6, "label6");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label5, "label5");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label4, "label4");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image1, "image1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label7, "label7");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image2, "image2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label8, "label8");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label2, "label2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label3, "label3");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, jour, "jour");

  return fenetre_ajout;
}

GtkWidget*
create_fenetre_affiche_ (void)
{
  GtkWidget *fenetre_affiche_;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *retour;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label10;

  fenetre_affiche_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_affiche_), _("window1"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (fenetre_affiche_), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 120, 88);
  gtk_widget_set_size_request (treeview1, 300, 200);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed3), retour, 184, 320);
  gtk_widget_set_size_request (retour, 150, 30);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (retour), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Retourner "));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox3), label10, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_affiche_, fenetre_affiche_, "fenetre_affiche_");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_, retour, "retour");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_, image3, "image3");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_, label10, "label10");

  return fenetre_affiche_;
}

GtkWidget*
create_fenetre_chercher (void)
{
  GtkWidget *fenetre_chercher;
  GtkWidget *fixed7;
  GtkWidget *type3;
  GtkWidget *type;
  GtkWidget *chercher;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label21;

  fenetre_chercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_chercher), _("Chercher une plantation "));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (fenetre_chercher), fixed7);

  type3 = gtk_entry_new ();
  gtk_widget_show (type3);
  gtk_fixed_put (GTK_FIXED (fixed7), type3, 144, 100);
  gtk_widget_set_size_request (type3, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (type3), 8226);

  type = gtk_label_new (_("Type : "));
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed7), type, 40, 100);
  gtk_widget_set_size_request (type, 150, 30);

  chercher = gtk_button_new ();
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed7), chercher, 184, 192);
  gtk_widget_set_size_request (chercher, 150, 30);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (chercher), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox6), label21, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) chercher, "clicked",
                    G_CALLBACK (on_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_chercher, fenetre_chercher, "fenetre_chercher");
  GLADE_HOOKUP_OBJECT (fenetre_chercher, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (fenetre_chercher, type3, "type3");
  GLADE_HOOKUP_OBJECT (fenetre_chercher, type, "type");
  GLADE_HOOKUP_OBJECT (fenetre_chercher, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (fenetre_chercher, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (fenetre_chercher, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (fenetre_chercher, image6, "image6");
  GLADE_HOOKUP_OBJECT (fenetre_chercher, label21, "label21");

  return fenetre_chercher;
}

GtkWidget*
create_fenetre_supprime (void)
{
  GtkWidget *fenetre_supprime;
  GtkWidget *fixed8;
  GtkWidget *type;
  GtkWidget *type2;
  GtkWidget *supprime;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label23;

  fenetre_supprime = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_supprime), _("Supprimer une plantation "));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (fenetre_supprime), fixed8);

  type = gtk_label_new (_("Type de la plante : "));
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed8), type, 72, 88);
  gtk_widget_set_size_request (type, 150, 30);

  type2 = gtk_entry_new ();
  gtk_widget_show (type2);
  gtk_fixed_put (GTK_FIXED (fixed8), type2, 216, 88);
  gtk_widget_set_size_request (type2, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (type2), 8226);

  supprime = gtk_button_new ();
  gtk_widget_show (supprime);
  gtk_fixed_put (GTK_FIXED (fixed8), supprime, 216, 184);
  gtk_widget_set_size_request (supprime, 150, 30);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (supprime), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox7), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) supprime, "clicked",
                    G_CALLBACK (on_supprime_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_supprime, fenetre_supprime, "fenetre_supprime");
  GLADE_HOOKUP_OBJECT (fenetre_supprime, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (fenetre_supprime, type, "type");
  GLADE_HOOKUP_OBJECT (fenetre_supprime, type2, "type2");
  GLADE_HOOKUP_OBJECT (fenetre_supprime, supprime, "supprime");
  GLADE_HOOKUP_OBJECT (fenetre_supprime, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (fenetre_supprime, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (fenetre_supprime, image7, "image7");
  GLADE_HOOKUP_OBJECT (fenetre_supprime, label23, "label23");

  return fenetre_supprime;
}

GtkWidget*
create_fenetre_modife (void)
{
  GtkWidget *fenetre_modife;
  GtkWidget *fixed9;
  GtkWidget *type4;
  GtkObject *jour4_adj;
  GtkWidget *jour4;
  GtkObject *mois4_adj;
  GtkWidget *mois4;
  GtkObject *annee4_adj;
  GtkWidget *annee4;
  GtkWidget *quantite4;
  GtkWidget *annee;
  GtkWidget *mois;
  GtkWidget *jour;
  GtkWidget *saison_;
  GtkWidget *type;
  GtkWidget *quantite;
  GtkWidget *modifier;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label30;

  fenetre_modife = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_modife), _("Modifier une plantation "));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (fenetre_modife), fixed9);

  type4 = gtk_entry_new ();
  gtk_widget_show (type4);
  gtk_fixed_put (GTK_FIXED (fixed9), type4, 240, 80);
  gtk_widget_set_size_request (type4, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (type4), 8226);

  jour4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour4 = gtk_spin_button_new (GTK_ADJUSTMENT (jour4_adj), 1, 0);
  gtk_widget_show (jour4);
  gtk_fixed_put (GTK_FIXED (fixed9), jour4, 224, 144);
  gtk_widget_set_size_request (jour4, 60, 27);

  mois4_adj = gtk_adjustment_new (1, 0, 100, 1, 12, 10);
  mois4 = gtk_spin_button_new (GTK_ADJUSTMENT (mois4_adj), 1, 0);
  gtk_widget_show (mois4);
  gtk_fixed_put (GTK_FIXED (fixed9), mois4, 360, 144);
  gtk_widget_set_size_request (mois4, 60, 27);

  annee4_adj = gtk_adjustment_new (1990, 1990, 2020, 1, 10, 10);
  annee4 = gtk_spin_button_new (GTK_ADJUSTMENT (annee4_adj), 1, 0);
  gtk_widget_show (annee4);
  gtk_fixed_put (GTK_FIXED (fixed9), annee4, 544, 144);
  gtk_widget_set_size_request (annee4, 60, 27);

  quantite4 = gtk_entry_new ();
  gtk_widget_show (quantite4);
  gtk_fixed_put (GTK_FIXED (fixed9), quantite4, 184, 216);
  gtk_widget_set_size_request (quantite4, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (quantite4), 8226);

  annee = gtk_label_new (_("annee :"));
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed9), annee, 440, 144);
  gtk_widget_set_size_request (annee, 150, 30);

  mois = gtk_label_new (_("mois : "));
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed9), mois, 256, 144);
  gtk_widget_set_size_request (mois, 150, 30);

  jour = gtk_label_new (_("Jour : "));
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed9), jour, 176, 152);
  gtk_widget_set_size_request (jour, 49, 17);

  saison_ = gtk_label_new (_("Nouvelle saison : "));
  gtk_widget_show (saison_);
  gtk_fixed_put (GTK_FIXED (fixed9), saison_, 24, 144);
  gtk_widget_set_size_request (saison_, 150, 30);

  type = gtk_label_new (_("Type de la plante \303\240 modifier :"));
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed9), type, 0, 80);
  gtk_widget_set_size_request (type, 272, 30);

  quantite = gtk_label_new (_("Nouvelle quantit\303\251 : "));
  gtk_widget_show (quantite);
  gtk_fixed_put (GTK_FIXED (fixed9), quantite, 32, 216);
  gtk_widget_set_size_request (quantite, 150, 30);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed9), modifier, 224, 288);
  gtk_widget_set_size_request (modifier, 150, 30);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (modifier), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Enregistrer "));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox8), label30, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_modife, fenetre_modife, "fenetre_modife");
  GLADE_HOOKUP_OBJECT (fenetre_modife, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (fenetre_modife, type4, "type4");
  GLADE_HOOKUP_OBJECT (fenetre_modife, jour4, "jour4");
  GLADE_HOOKUP_OBJECT (fenetre_modife, mois4, "mois4");
  GLADE_HOOKUP_OBJECT (fenetre_modife, annee4, "annee4");
  GLADE_HOOKUP_OBJECT (fenetre_modife, quantite4, "quantite4");
  GLADE_HOOKUP_OBJECT (fenetre_modife, annee, "annee");
  GLADE_HOOKUP_OBJECT (fenetre_modife, mois, "mois");
  GLADE_HOOKUP_OBJECT (fenetre_modife, jour, "jour");
  GLADE_HOOKUP_OBJECT (fenetre_modife, saison_, "saison_");
  GLADE_HOOKUP_OBJECT (fenetre_modife, type, "type");
  GLADE_HOOKUP_OBJECT (fenetre_modife, quantite, "quantite");
  GLADE_HOOKUP_OBJECT (fenetre_modife, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (fenetre_modife, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (fenetre_modife, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (fenetre_modife, image8, "image8");
  GLADE_HOOKUP_OBJECT (fenetre_modife, label30, "label30");

  return fenetre_modife;
}

