/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_plantation_vegetale (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_affiche_ (void);
GtkWidget* create_fenetre_chercher (void);
GtkWidget* create_fenetre_supprime (void);
GtkWidget* create_fenetre_modife (void);
