/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_InterfaceAjout_a (void)
{
  GtkWidget *InterfaceAjout_a;
  GtkWidget *fixed4;
  GtkWidget *IdArr;
  GtkWidget *IdEntry;
  GtkWidget *label27;
  GtkObject *spinbuttonJ_adj;
  GtkWidget *spinbuttonJ;
  GtkObject *spinbuttonM_adj;
  GtkWidget *spinbuttonM;
  GtkObject *spinbuttonA_adj;
  GtkWidget *spinbuttonA;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label25;
  GtkWidget *button17;
  GtkWidget *image16;
  GtkWidget *button9;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image9;
  GtkWidget *label28;
  GtkWidget *DateArr;
  GtkWidget *ControlArr;

  InterfaceAjout_a = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (InterfaceAjout_a), _("AjoutArrosage"));
  gtk_window_set_default_size (GTK_WINDOW (InterfaceAjout_a), 500, 300);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (InterfaceAjout_a), fixed4);

  IdArr = gtk_label_new (_("ID plante :"));
  gtk_widget_show (IdArr);
  gtk_fixed_put (GTK_FIXED (fixed4), IdArr, 16, 88);
  gtk_widget_set_size_request (IdArr, 72, 25);

  IdEntry = gtk_entry_new ();
  gtk_widget_show (IdEntry);
  gtk_fixed_put (GTK_FIXED (fixed4), IdEntry, 96, 88);
  gtk_widget_set_size_request (IdEntry, 72, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (IdEntry), 8226);

  label27 = gtk_label_new (_("Date d'arrosage :"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 16, 136);
  gtk_widget_set_size_request (label27, 120, 25);

  spinbuttonJ_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonJ = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJ_adj), 1, 0);
  gtk_widget_show (spinbuttonJ);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonJ, 152, 136);
  gtk_widget_set_size_request (spinbuttonJ, 48, 27);

  spinbuttonM_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonM_adj), 1, 0);
  gtk_widget_show (spinbuttonM);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonM, 216, 136);
  gtk_widget_set_size_request (spinbuttonM, 48, 27);

  spinbuttonA_adj = gtk_adjustment_new (1, 0, 5000, 1, 10, 10);
  spinbuttonA = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonA_adj), 1, 0);
  gtk_widget_show (spinbuttonA);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonA, 272, 136);
  gtk_widget_set_size_request (spinbuttonA, 60, 27);

  label29 = gtk_label_new (_("JJ"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 160, 168);
  gtk_widget_set_size_request (label29, 32, 17);

  label30 = gtk_label_new (_("MM"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 224, 168);
  gtk_widget_set_size_request (label30, 32, 17);

  label31 = gtk_label_new (_("AA"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed4), label31, 288, 168);
  gtk_widget_set_size_request (label31, 32, 17);

  label25 = gtk_label_new (_("Ajouter Arrosage"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 184, 8);
  gtk_widget_set_size_request (label25, 144, 33);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed4), button17, 8, 8);
  gtk_widget_set_size_request (button17, 32, 29);

  image16 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (button17), image16);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed4), button9, 200, 256);
  gtk_widget_set_size_request (button9, 88, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button9), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox7), image9, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox7), label28, FALSE, FALSE, 0);

  DateArr = gtk_label_new ("");
  gtk_widget_show (DateArr);
  gtk_fixed_put (GTK_FIXED (fixed4), DateArr, 152, 192);
  gtk_widget_set_size_request (DateArr, 176, 16);

  ControlArr = gtk_label_new ("");
  gtk_widget_show (ControlArr);
  gtk_fixed_put (GTK_FIXED (fixed4), ControlArr, 32, 232);
  gtk_widget_set_size_request (ControlArr, 448, 17);

  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (RedirectAffArr),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (AddArrosage),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (InterfaceAjout_a, InterfaceAjout_a, "InterfaceAjout_a");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, IdArr, "IdArr");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, IdEntry, "IdEntry");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, label27, "label27");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, spinbuttonJ, "spinbuttonJ");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, spinbuttonM, "spinbuttonM");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, spinbuttonA, "spinbuttonA");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, label29, "label29");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, label30, "label30");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, label31, "label31");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, label25, "label25");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, button17, "button17");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, image16, "image16");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, button9, "button9");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, image9, "image9");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, label28, "label28");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, DateArr, "DateArr");
  GLADE_HOOKUP_OBJECT (InterfaceAjout_a, ControlArr, "ControlArr");

  return InterfaceAjout_a;
}

GtkWidget*
create_InterfaceAfficher_a (void)
{
  GtkWidget *InterfaceAfficher_a;
  GtkWidget *fixed5;
  GtkWidget *label32;
  GtkWidget *treeview2;
  GtkWidget *SearchEntryArr;
  GtkWidget *button12;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image12;
  GtkWidget *label35;
  GtkWidget *button11;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image11;
  GtkWidget *label34;
  GtkWidget *button13;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image13;
  GtkWidget *label36;
  GtkWidget *SearchCnt;
  GtkWidget *button10;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image10;
  GtkWidget *label33;
  GtkWidget *button14;
  GtkWidget *image14;
  GtkWidget *vseparator1;
  GtkWidget *hseparator1;
  GtkWidget *hseparator2;
  GtkWidget *button20;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label55;

  InterfaceAfficher_a = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (InterfaceAfficher_a), _("InterfaceAfficher_a"));
  gtk_window_set_default_size (GTK_WINDOW (InterfaceAfficher_a), 500, 500);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (InterfaceAfficher_a), fixed5);

  label32 = gtk_label_new (_("Afficher Liste d'arrosage "));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 168, 8);
  gtk_widget_set_size_request (label32, 176, 40);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview2, 16, 112);
  gtk_widget_set_size_request (treeview2, 248, 296);

  SearchEntryArr = gtk_entry_new ();
  gtk_widget_show (SearchEntryArr);
  gtk_fixed_put (GTK_FIXED (fixed5), SearchEntryArr, 312, 64);
  gtk_widget_set_size_request (SearchEntryArr, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (SearchEntryArr), 8226);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed5), button12, 344, 264);
  gtk_widget_set_size_request (button12, 104, 37);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button12), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox10), image12, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox10), label35, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed5), button11, 344, 200);
  gtk_widget_set_size_request (button11, 104, 37);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button11), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image11 = gtk_image_new_from_stock ("gtk-color-picker", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox9), image11, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox9), label34, FALSE, FALSE, 0);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed5), button13, 344, 328);
  gtk_widget_set_size_request (button13, 104, 37);
  gtk_button_set_focus_on_click (GTK_BUTTON (button13), FALSE);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button13), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image13 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox11), image13, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Actualiser "));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox11), label36, FALSE, FALSE, 0);

  SearchCnt = gtk_label_new ("");
  gtk_widget_show (SearchCnt);
  gtk_fixed_put (GTK_FIXED (fixed5), SearchCnt, 296, 96);
  gtk_widget_set_size_request (SearchCnt, 40, 32);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed5), button10, 344, 144);
  gtk_widget_set_size_request (button10, 104, 37);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button10), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image10 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox8), image10, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox8), label33, FALSE, FALSE, 0);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed5), button14, 272, 64);
  gtk_widget_set_size_request (button14, 32, 29);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_container_add (GTK_CONTAINER (button14), image14);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed5), vseparator1, 296, 112);
  gtk_widget_set_size_request (vseparator1, 16, 296);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed5), hseparator1, 8, 408);
  gtk_widget_set_size_request (hseparator1, 488, 24);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed5), hseparator2, 8, 96);
  gtk_widget_set_size_request (hseparator2, 488, 16);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed5), button20, 328, 432);
  gtk_widget_set_size_request (button20, 160, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button20), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image19 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Ann\303\251\303\251 Plus S\303\250che "));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox15), label55, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (RedirectAdd),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (RedirectUpdate),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (RefreshArr),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (RemoveArr),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (ChercherArr),
                    NULL);
  g_signal_connect ((gpointer) button20, "clicked",
                    G_CALLBACK (AnneeSeche),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (InterfaceAfficher_a, InterfaceAfficher_a, "InterfaceAfficher_a");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, label32, "label32");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, SearchEntryArr, "SearchEntryArr");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, button12, "button12");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, image12, "image12");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, label35, "label35");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, button11, "button11");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, image11, "image11");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, label34, "label34");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, button13, "button13");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, image13, "image13");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, label36, "label36");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, SearchCnt, "SearchCnt");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, button10, "button10");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, image10, "image10");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, label33, "label33");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, button14, "button14");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, image14, "image14");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, button20, "button20");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, image19, "image19");
  GLADE_HOOKUP_OBJECT (InterfaceAfficher_a, label55, "label55");

  return InterfaceAfficher_a;
}

GtkWidget*
create_InterfaceUpdate_a (void)
{
  GtkWidget *InterfaceUpdate_a;
  GtkWidget *fixed6;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *entry2;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label39;
  GtkWidget *label44;
  GtkWidget *entry3;
  GtkWidget *button15;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image15;
  GtkWidget *label43;
  GtkWidget *DateArr1;
  GtkWidget *cntrsaisie;

  InterfaceUpdate_a = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (InterfaceUpdate_a), _("ModifierArrosage"));
  gtk_window_set_default_size (GTK_WINDOW (InterfaceUpdate_a), 500, 300);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (InterfaceUpdate_a), fixed6);

  label37 = gtk_label_new (_("Modifier Arrosage"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed6), label37, 184, 8);
  gtk_widget_set_size_request (label37, 136, 25);

  label38 = gtk_label_new (_("ID plante :"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed6), label38, 16, 104);
  gtk_widget_set_size_request (label38, 80, 25);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed6), entry2, 104, 104);
  gtk_widget_set_size_request (entry2, 80, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton2, 152, 160);
  gtk_widget_set_size_request (spinbutton2, 48, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton3, 216, 160);
  gtk_widget_set_size_request (spinbutton3, 48, 27);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 5000, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton4, 272, 160);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  label40 = gtk_label_new (_("JJ"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed6), label40, 160, 192);
  gtk_widget_set_size_request (label40, 32, 17);

  label41 = gtk_label_new (_("MM"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed6), label41, 224, 192);
  gtk_widget_set_size_request (label41, 32, 17);

  label42 = gtk_label_new (_("AA"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed6), label42, 288, 192);
  gtk_widget_set_size_request (label42, 32, 16);

  label39 = gtk_label_new (_("Date d'arrosage : "));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 16, 160);
  gtk_widget_set_size_request (label39, 120, 25);

  label44 = gtk_label_new (_("Saisie l'ID du plante que vous voulez modifier :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed6), label44, 0, 64);
  gtk_widget_set_size_request (label44, 352, 16);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed6), entry3, 360, 56);
  gtk_widget_set_size_request (entry3, 80, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed6), button15, 200, 248);
  gtk_widget_set_size_request (button15, 88, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button15), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image15 = gtk_image_new_from_stock ("gtk-color-picker", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox12), image15, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox12), label43, FALSE, FALSE, 0);

  DateArr1 = gtk_label_new ("");
  gtk_widget_show (DateArr1);
  gtk_fixed_put (GTK_FIXED (fixed6), DateArr1, 336, 160);
  gtk_widget_set_size_request (DateArr1, 152, 32);

  cntrsaisie = gtk_label_new ("");
  gtk_widget_show (cntrsaisie);
  gtk_fixed_put (GTK_FIXED (fixed6), cntrsaisie, 48, 216);
  gtk_widget_set_size_request (cntrsaisie, 416, 16);

  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (UpdateArrFn),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (InterfaceUpdate_a, InterfaceUpdate_a, "InterfaceUpdate_a");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, label37, "label37");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, label38, "label38");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, label40, "label40");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, label41, "label41");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, label42, "label42");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, label39, "label39");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, label44, "label44");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, button15, "button15");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, image15, "image15");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, label43, "label43");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, DateArr1, "DateArr1");
  GLADE_HOOKUP_OBJECT (InterfaceUpdate_a, cntrsaisie, "cntrsaisie");

  return InterfaceUpdate_a;
}

