/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_home (void);
GtkWidget* create_ajout (void);
GtkWidget* create_search (void);
GtkWidget* create_modifier (void);
GtkWidget* create_window1 (void);
GtkWidget* create_success (void);
GtkWidget* create_failed (void);
GtkWidget* create_Absence (void);
GtkWidget* create_MrqAbs (void);
GtkWidget* create_tauxdab (void);
GtkWidget* create_txs (void);
GtkWidget* create_connexion (void);
GtkWidget* create_admin (void);
GtkWidget* create_Mestroupeaux (void);
GtkWidget* create_Ajouterunanimal (void);
GtkWidget* create_afficher (void);
GtkWidget* create_modiff (void);
GtkWidget* create_type (void);
GtkWidget* create_InterfaceAjout_a (void);
GtkWidget* create_InterfaceAfficher_a (void);
GtkWidget* create_InterfaceUpdate_a (void);
GtkWidget* create_menu (void);
