/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *home;
  GtkWidget *ajout;
  GtkWidget *search;
  GtkWidget *modifier;
  GtkWidget *window1;
  GtkWidget *success;
  GtkWidget *failed;
  GtkWidget *Absence;
  GtkWidget *MrqAbs;
  GtkWidget *tauxdab;
  GtkWidget *txs;
  GtkWidget *connexion;
  GtkWidget *admin;
  GtkWidget *adminmenu;
  GtkWidget *Mestroupeaux;
  GtkWidget *Ajouterunanimal;
  GtkWidget *afficher;
  GtkWidget *modiff;
  GtkWidget *type;
  GtkWidget *InterfaceAjout_a;
  GtkWidget *InterfaceAfficher_a;
  GtkWidget *InterfaceUpdate_a;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);
add_pixmap_directory ("../pixmaps");
  

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  
  connexion = create_connexion ();
  gtk_widget_show (connexion);
  

  gtk_main ();
  return 0;
}

