/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Mestroupeaux (void)
{
  GtkWidget *Mestroupeaux;
  GtkWidget *fixed1;
  GtkWidget *fixed4;
  GtkWidget *buttonAfficher;
  GtkWidget *fixed3;
  GtkWidget *fixed2;
  GtkWidget *label1;
  GtkWidget *buttontype;
  GtkWidget *buttonModifier;
  GtkWidget *buttonAjout;

  Mestroupeaux = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Mestroupeaux), _("Mestroupeaux"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Mestroupeaux), fixed1);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_fixed_put (GTK_FIXED (fixed1), fixed4, 48, 160);
  gtk_widget_set_size_request (fixed4, 50, 50);

  buttonAfficher = gtk_button_new_with_mnemonic (_("Afficher les coordon\303\251es de mes troupeaux"));
  gtk_widget_show (buttonAfficher);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonAfficher, 152, 88);
  gtk_widget_set_size_request (buttonAfficher, 296, 40);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_fixed_put (GTK_FIXED (fixed1), fixed3, 176, 88);
  gtk_widget_set_size_request (fixed3, 50, 50);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_fixed_put (GTK_FIXED (fixed1), fixed2, 120, 144);
  gtk_widget_set_size_request (fixed2, 50, 50);

  label1 = gtk_label_new (_("Gestion des troupeaux"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 248, 24);
  gtk_widget_set_size_request (label1, 232, 32);

  buttontype = gtk_button_new_with_mnemonic (_("Le nombre de troupeaux de chaque type"));
  gtk_widget_show (buttontype);
  gtk_fixed_put (GTK_FIXED (fixed1), buttontype, 200, 320);
  gtk_widget_set_size_request (buttontype, 296, 40);

  buttonModifier = gtk_button_new_with_mnemonic (_("Modifier les coordonn\303\251es d'un animal"));
  gtk_widget_show (buttonModifier);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonModifier, 200, 160);
  gtk_widget_set_size_request (buttonModifier, 296, 40);

  buttonAjout = gtk_button_new_with_mnemonic (_("Ajouter un animal"));
  gtk_widget_show (buttonAjout);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAjout, 200, 88);
  gtk_widget_set_size_request (buttonAjout, 296, 40);

  g_signal_connect ((gpointer) buttonAfficher, "clicked",
                    G_CALLBACK (on_buttonAfficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttontype, "clicked",
                    G_CALLBACK (on_buttontype_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifier, "clicked",
                    G_CALLBACK (on_buttonModifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjout, "clicked",
                    G_CALLBACK (on_buttonAjout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Mestroupeaux, Mestroupeaux, "Mestroupeaux");
  GLADE_HOOKUP_OBJECT (Mestroupeaux, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Mestroupeaux, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Mestroupeaux, buttonAfficher, "buttonAfficher");
  GLADE_HOOKUP_OBJECT (Mestroupeaux, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Mestroupeaux, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Mestroupeaux, label1, "label1");
  GLADE_HOOKUP_OBJECT (Mestroupeaux, buttontype, "buttontype");
  GLADE_HOOKUP_OBJECT (Mestroupeaux, buttonModifier, "buttonModifier");
  GLADE_HOOKUP_OBJECT (Mestroupeaux, buttonAjout, "buttonAjout");

  return Mestroupeaux;
}

GtkWidget*
create_Ajouterunanimal (void)
{
  GtkWidget *Ajouterunanimal;
  GtkWidget *fixed5;
  GtkWidget *id;
  GtkObject *Jour_adj;
  GtkWidget *Jour;
  GtkObject *Mois_adj;
  GtkWidget *Mois;
  GtkObject *Annee_adj;
  GtkWidget *Annee;
  GtkWidget *label9;
  GtkWidget *label5;
  GtkWidget *retour;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label8;
  GtkWidget *ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *label4;
  GtkWidget *label3;
  GtkWidget *label10;
  GtkWidget *label2;
  GtkWidget *label6;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *combobox1;

  Ajouterunanimal = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouterunanimal), _("Ajouterunanimal"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Ajouterunanimal), fixed5);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed5), id, 240, 88);
  gtk_widget_set_size_request (id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  Jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  Jour = gtk_spin_button_new (GTK_ADJUSTMENT (Jour_adj), 1, 1);
  gtk_widget_show (Jour);
  gtk_fixed_put (GTK_FIXED (fixed5), Jour, 184, 144);
  gtk_widget_set_size_request (Jour, 48, 24);

  Mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  Mois = gtk_spin_button_new (GTK_ADJUSTMENT (Mois_adj), 1, 0);
  gtk_widget_show (Mois);
  gtk_fixed_put (GTK_FIXED (fixed5), Mois, 296, 144);
  gtk_widget_set_size_request (Mois, 56, 24);

  Annee_adj = gtk_adjustment_new (1, 2000, 2021, 1, 10, 10);
  Annee = gtk_spin_button_new (GTK_ADJUSTMENT (Annee_adj), 1, 0);
  gtk_widget_show (Annee);
  gtk_fixed_put (GTK_FIXED (fixed5), Annee, 432, 144);
  gtk_widget_set_size_request (Annee, 60, 27);

  label9 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed5), label9, 16, 184);
  gtk_widget_set_size_request (label9, 136, 40);
  gtk_misc_set_alignment (GTK_MISC (label9), 0.5, 0.53);
  gtk_misc_set_padding (GTK_MISC (label9), 0, 2);

  label5 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed5), label5, 344, 136);
  gtk_widget_set_size_request (label5, 96, 40);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed5), retour, 288, 312);
  gtk_widget_set_size_request (retour, 152, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (retour), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox2), label8, FALSE, FALSE, 0);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed5), ajouter, 40, 312);
  gtk_widget_set_size_request (ajouter, 128, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed5), label4, 224, 136);
  gtk_widget_set_size_request (label4, 88, 40);

  label3 = gtk_label_new (_("Date de naissance : Jour :"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed5), label3, 0, 152);
  gtk_widget_set_size_request (label3, 200, 16);

  label10 = gtk_label_new (_("Type :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed5), label10, 0, 240);
  gtk_widget_set_size_request (label10, 168, 32);

  label2 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed5), label2, 0, 80);
  gtk_widget_set_size_request (label2, 192, 40);

  label6 = gtk_label_new (_("Formulaire d'ajout d'un nouvel animal"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed5), label6, 64, 16);
  gtk_widget_set_size_request (label6, 352, 56);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Belier"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton1, 176, 240);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Veau"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton2, 328, 240);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox1, 160, 192);
  gtk_widget_set_size_request (combobox1, 128, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("male "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("femelle"));

  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouterunanimal, Ajouterunanimal, "Ajouterunanimal");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, id, "id");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, Jour, "Jour");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, Mois, "Mois");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, Annee, "Annee");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, label9, "label9");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, label5, "label5");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, retour, "retour");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, image2, "image2");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, label8, "label8");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, image1, "image1");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, label7, "label7");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, label4, "label4");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, label3, "label3");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, label10, "label10");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, label2, "label2");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, label6, "label6");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (Ajouterunanimal, combobox1, "combobox1");

  return Ajouterunanimal;
}

GtkWidget*
create_afficher (void)
{
  GtkWidget *afficher;
  GtkWidget *fixed6;
  GtkWidget *treeview1;
  GtkWidget *retouraff;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label11;

  afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afficher), _("afficher"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (afficher), fixed6);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview1, 176, 32);
  gtk_widget_set_size_request (treeview1, 300, 200);

  retouraff = gtk_button_new ();
  gtk_widget_show (retouraff);
  gtk_fixed_put (GTK_FIXED (fixed6), retouraff, 280, 280);
  gtk_widget_set_size_request (retouraff, 120, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (retouraff), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) retouraff, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (afficher, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (afficher, retouraff, "retouraff");
  GLADE_HOOKUP_OBJECT (afficher, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (afficher, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (afficher, image3, "image3");
  GLADE_HOOKUP_OBJECT (afficher, label11, "label11");

  return afficher;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed7;
  GtkWidget *entry1;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *id;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *fixed8;
  GtkWidget *radiobutton6;
  GSList *radiobutton6_group = NULL;
  GtkWidget *retourmodif;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label21;
  GtkWidget *buttonmodifier;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label20;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton7;
  GtkWidget *label17;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("modifier"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (modifier), fixed7);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed7), entry1, 208, 16);
  gtk_widget_set_size_request (entry1, 144, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton1, 176, 104);
  gtk_widget_set_size_request (spinbutton1, 48, 24);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton2, 272, 104);
  gtk_widget_set_size_request (spinbutton2, 48, 24);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton3, 376, 104);
  gtk_widget_set_size_request (spinbutton3, 48, 24);

  label12 = gtk_label_new (_("L'ID de l'animal \303\240 modifier : "));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed7), label12, 16, 16);
  gtk_widget_set_size_request (label12, 192, 24);

  label13 = gtk_label_new (_("Les coordonn\303\251es \303\240 modifier:"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed7), label13, 104, 48);
  gtk_widget_set_size_request (label13, 208, 16);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed7), id, 40, 72);
  gtk_widget_set_size_request (id, 144, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  label14 = gtk_label_new (_("Date de naissance: Jour :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed7), label14, 0, 104);
  gtk_widget_set_size_request (label14, 184, 16);

  label15 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed7), label15, 224, 104);
  gtk_widget_set_size_request (label15, 49, 17);

  label16 = gtk_label_new (_("Ann\303\251e:"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed7), label16, 328, 104);
  gtk_widget_set_size_request (label16, 49, 17);

  label18 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed7), label18, 8, 136);
  gtk_widget_set_size_request (label18, 64, 24);

  label19 = gtk_label_new (_("Type : "));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed7), label19, 16, 168);
  gtk_widget_set_size_request (label19, 49, 17);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_fixed_put (GTK_FIXED (fixed7), fixed8, 64, 168);
  gtk_widget_set_size_request (fixed8, 50, 50);

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("Brebi"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton6, 24, 0);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  retourmodif = gtk_button_new ();
  gtk_widget_show (retourmodif);
  gtk_fixed_put (GTK_FIXED (fixed7), retourmodif, 216, 208);
  gtk_widget_set_size_request (retourmodif, 112, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (retourmodif), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox5), label21, FALSE, FALSE, 0);

  buttonmodifier = gtk_button_new ();
  gtk_widget_show (buttonmodifier);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonmodifier, 48, 208);
  gtk_widget_set_size_request (buttonmodifier, 112, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonmodifier), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox4), label20, FALSE, FALSE, 0);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("male"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton4, 88, 136);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("femelle"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton5, 216, 136);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Veau"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton7, 216, 168);
  gtk_widget_set_size_request (radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  label17 = gtk_label_new (_("ID :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed7), label17, 0, 72);
  gtk_widget_set_size_request (label17, 49, 17);

  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (on_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) retourmodif, "clicked",
                    G_CALLBACK (on_retourmodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier, "clicked",
                    G_CALLBACK (on_buttonmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton7, "toggled",
                    G_CALLBACK (on_radiobutton7_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (modifier, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (modifier, label12, "label12");
  GLADE_HOOKUP_OBJECT (modifier, label13, "label13");
  GLADE_HOOKUP_OBJECT (modifier, id, "id");
  GLADE_HOOKUP_OBJECT (modifier, label14, "label14");
  GLADE_HOOKUP_OBJECT (modifier, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifier, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifier, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (modifier, retourmodif, "retourmodif");
  GLADE_HOOKUP_OBJECT (modifier, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (modifier, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (modifier, image5, "image5");
  GLADE_HOOKUP_OBJECT (modifier, label21, "label21");
  GLADE_HOOKUP_OBJECT (modifier, buttonmodifier, "buttonmodifier");
  GLADE_HOOKUP_OBJECT (modifier, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (modifier, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (modifier, image4, "image4");
  GLADE_HOOKUP_OBJECT (modifier, label20, "label20");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (modifier, label17, "label17");

  return modifier;
}

