/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Mestroupeaux (void);
GtkWidget* create_Ajouterunanimal (void);
GtkWidget* create_afficher (void);
GtkWidget* create_modifier (void);
GtkWidget* create_type (void);
